apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: senior-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: senior-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: senior-cluster-read-only-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test
  name: senior-rolebinding
subjects:
  - kind: Group
    name: senior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: production
  name: senior-rolebinding
subjects:
  - kind: Group
    name: senior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: senior-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: senior-cluster-read-only-rolebinding
subjects:
  - kind: Group
    name: senior
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: senior-cluster-read-only-role
  apiGroup: rbac.authorization.k8s.io