apiVersion: v1
kind: Pod
metadata:
  name: pod-reader
  namespace: kube-system
spec:
  serviceAccountName: pod-reader
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"